### ISSUE TITLE
codestyle.xml

### ISSUE THREAD

**Issue by rnc** [release-engineering/koji-build-finder#5]
Add a formatter for Eclipse/IntelliJ to comply with the checkstyle formatting.

**Comment by rnc** [comment]
Also need to document what 'style' this checkstyle.xml matches with

**Comment by dwalluck** [comment]
The style is a subset of the Sun style, so the Sun style or default Eclipse style should work.

**Comment by dwalluck** [comment]
The style also enforces Unix line-endings and no trailing whitespace. In Eclipse, you can set it to remove trailing whitespace in Java > Editor > Save Actions.

**Comment by rnc** [comment]
@dwalluck What about for IntelliJ ? ;-)

**Comment by dwalluck** [comment]
I am not so familiar with IntelliJ, e.g., how the code style is changed. The default style may work.

Editor > Code > Line separator (for new files): UNIX and OS X (\n)
Editor > General > Strip Trailing Spaces on Save: All
